/* 테이블 생성 */
CREATE TABLE CATEGORY( 
	CATENUM INT PRIMARY KEY,
	CATEL VARCHAR(50),
	CATEM VARCHAR(50)
);

CREATE TABLE PRODUCT( 
	PNUM INT AUTO_INCREMENT PRIMARY KEY,
	CATENUM INT,
	PNAME VARCHAR(100) NOT NULL,
	FIXPRICE INT DEFAULT 0,
	SELPRICE INT DEFAULT 0,
	RDATE DATETIME,
	REPERSON VARCHAR(20),
	REAGE INT,
	BRAND VARCHAR(50),
	PIMG VARCHAR(1000) NOT NULL,
	INFOIMG VARCHAR(1000) NOT NULL,
	PRODUCTCNT INT DEFAULT 50,
	CONSTRAINT PRODUCT_CATEGORY_FK FOREIGN KEY (CATENUM) REFERENCES CATEGORY(CATENUM) ON DELETE CASCADE
);


CREATE TABLE MEMBER( 
   MNUM INT AUTO_INCREMENT PRIMARY KEY,
   MID VARCHAR(30) NOT NULL, 
   MPW VARCHAR(30) NOT NULL,  
   MNAME VARCHAR(30) NOT NULL,
   MEMAIL VARCHAR(100),
   MTEL VARCHAR(100),
   MPOINT INT,
   ZIPCODE VARCHAR(50),
   USERADDR VARCHAR(100),
   DETAILADDR VARCHAR(100),
   MDATE DATETIME,
   KAKAOLOGIN VARCHAR(100),
   SOCRE INT DEFAULT 0,
   MSTATUS VARCHAR(1) DEFAULT '0',
   CONSTRAINT MSTATUS_BL CHECK(MSTATUS IN('0','1')),
   CONSTRAINT MEMAIL_UQ UNIQUE (MEMAIL)
);

CREATE TABLE DIB( 
   	DIBNUM INT AUTO_INCREMENT PRIMARY KEY,
	PNUM INT,
	MNUM INT,
	DCNT INT,
	CONSTRAINT DIB_PRODUCT_FK FOREIGN KEY (PNUM) REFERENCES PRODUCT(PNUM) ON DELETE CASCADE,
	CONSTRAINT DIB_MEMBER_FK FOREIGN KEY (MNUM) REFERENCES MEMBER(MNUM) ON DELETE CASCADE
);

CREATE TABLE ADDRESS( 
	ANUM INT AUTO_INCREMENT PRIMARY KEY,
	MNUM INT,
	SHIPNAME VARCHAR(20),
	DESTINATION VARCHAR(20),
	ZIPCODE VARCHAR(50),
	USERADDR VARCHAR(100),
	DETAILADDR VARCHAR(100),
	TEL VARCHAR(20),
	ISDEFAULT VARCHAR(1) DEFAULT '0',
	CONSTRAINT ISDEFAULT_BL CHECK(ISDEFAULT IN('0','1')),
	CONSTRAINT ADDRESS_MEMBER_FK FOREIGN KEY (MNUM) REFERENCES MEMBER(MNUM) ON DELETE CASCADE
);


CREATE TABLE MORDER(
	ONUM INT AUTO_INCREMENT PRIMARY KEY,
	MNUM INT,
	OSHIPNAME VARCHAR(20),
	OZIPCODE VARCHAR(50),
	OUSERADDR VARCHAR(100),
	ODETAILADDR VARCHAR(50),
	OTEL VARCHAR(20),
	ODATE DATETIME,
	OSTATUS INT,
	OPOINT INT,
	CONSTRAINT MORDER_MEMBER_FK FOREIGN KEY (MNUM) REFERENCES MEMBER(MNUM) ON DELETE CASCADE
);

CREATE TABLE ORDERDETAIL(
	ODNUM INT AUTO_INCREMENT PRIMARY KEY,			  
	ONUM INT,
	PNUM INT,
	CNT INT,
	CONSTRAINT ORDERDETAIL_MORDER_FK FOREIGN KEY (ONUM) REFERENCES MORDER(ONUM) ON DELETE CASCADE,
	CONSTRAINT ORDERDETAIL_PRODUCT_FK FOREIGN KEY (PNUM) REFERENCES PRODUCT(PNUM)
);

-- Oracle의 INSTR(1,2,3,4) 메서드는 MySQL에서 대체할 수 없기 때문에 해당 로직의 procedure 생성
DELIMITER //
 
CREATE DEFINER=`root`@`localhost` FUNCTION `modoodb`.`INSTR4`(p_str VARCHAR(8000), p_substr VARCHAR(255), p_start INT, p_occurrence INT) RETURNS int DETERMINISTIC
BEGIN
    DECLARE v_found INT DEFAULT p_occurrence;
    DECLARE v_pos INT DEFAULT p_start;
    lbl:
    WHILE 1=1 
	DO
SET v_pos = LOCATE(p_substr, p_str, v_pos);
 
IF v_pos IS NULL OR v_pos = 0 THEN RETURN v_pos;
END IF;

IF v_found = 1 THEN LEAVE lbl;
END IF;

SET v_found = v_found - 1;
SET v_pos = v_pos + 1;
END WHILE;
 
	RETURN v_pos;
END //
DELIMITER ;