package com.spring.biz.board;

import org.springframework.jdbc.core.JdbcTemplate;

public class BoardDAO {

	private JdbcTemplate jdbcTemplate;

	private final String SQL_INSERT = "INSERT INTO BOARD (BTITLE, BCONTENT, BRATE, BCNT, BDATE, BWDATE, BSTATUS, BLATITUDE, BLONGITUDE, BLOCAL) VALUES(?,?,?,?,SYSDATE(),SYSDATE(),0,?,?,?)";
	private final String SQL_UPDATE = "UPDATE BOARD SET BTITLE=?, BCONTENT=? BRATE=?, BCNT=?, BDATE=?, BCDATE=SYSDATE(), BLATITUDE=?, BLONGITUDE=? WHERE BNUM =?";
	private final String SQL_DELETE = "DELETE FROM BOARD WHERE BNUM=?";
	// 등록순
	private final String SQL_SELECTALL_REGISTER = "SELECT * FROM (SELECT BNUM, MNUM, BTITLE, BRATE, BCNT, BWDATE, BLOCAL, BACTION FROM BOARD WHERE BACTION=0 ORDER BY BWDATE ASC) AS A"
			+ "UNION ALL"
			+ "SELECT * FROM (SELECT BNUM, MNUM, BTITLE, BRATE, BCNT, BWDATE, BLOCAL, BACTION FROM BOARD WHERE BACTION=1 ORDER BY BWDATE ASC) AS B";
	// 시합 날짜순
	private final String SQL_SELECTALL_MATCH = "SELECT * FROM (SELECT BNUM, MNUM, BTITLE, BRATE, BCNT, BDATE, BLOCAL, BACTION FROM BOARD WHERE BACTION=0 ORDER BY BDATE ASC) AS A"
			+ "UNION ALL"
			+ "SELECT * FROM (SELECT BNUM, MNUM, BTITLE, BRATE, BCNT, BDATE, BLOCAL, BACTION FROM BOARD WHERE BACTION=1 ORDER BY BDATE ASC) AS B";
	// 지역 선택
	private final String SQL_SELECTALL_AREA = "SELCT * FROM BOARD WHERE BLOCAL=? ORDER BY BDATE ASC";
	// 날짜 선택
	private final String SQL_SELECTALL_DATE = "SELECT * FROM (SELECT * FROM (SELECT BNUM, MNUM, BTITLE, BRATE, BCNT, BDATE, BLOCAL, BACTION FROM BOARD WHERE BACTION=0 ORDER BY BDATE ASC) AS A"
			+ "SELECT * FROM (SELECT BNUM, MNUM, BTITLE, BRATE, BCNT, BDATE, BLOCAL, BACTION FROM BOARD WHERE BACTION=1 ORDER BY BDATE ASC) AS B)AS C"
			+ "WHERE BDATE BETWEEN SYSDATE-? AND SYSDATE-?";
	// 헤더 부분 전체 검색(수정해야함)
	private final String SQL_SELECTALL_SEARCH = "SELECT * FROM BOARD WHERE BTITLE,BCONTENT LIKE CONCAT('%',?,'%')";
	//글 관리 페이지 상태바
	private final String SQL_SELECTALL_STATUS = "SELECT COUNT(*)AS CNT FROM BOARD WHERE BACTION = ? ORDER BY BDATE ASC";
	//글 관리 페이지 글 목록
	private final String SQL_SELECTALL_TITLE= "SELECT * FROM board WHERE BACTION =? ORDER BY BDATE ASC LIMIT  0+?,9";
	//마이 페이지 내가 작성한 글 목록
	private final String SQL_MYBOARD_SELECTALL="SELECT BTITLE, BADDRERSS,LEFT(BDATE,10),RIGHT(BDATE,6), BCNT, BACTION FROM BOARD WHERE MNUM=? ORDER BY BNUM ASC";
	//마이 페이지 내가 신청한 매칭 목록
	private final String SQL_SELECTALL="";
	//글 상세 페이지
	final String MATCH_SELECTONE = "SELECT A.BNUM, B.BTITLE, B.BCONTENT, B.BRATE, B.BCNT, B.BDATE, B.BLOCAL,B.BADDRESS, B.BACTION from BOARD B, APPLICANT A where A.BNUM = B.BNUM and A.BNUM=?";
	//글 상세 페이지(신청자)
	final String USER_SELECTONE = "SELECT M.MNUM, M.MNAME, M.SCORE,B.BRATE, M.MIMG FROM MEMBER M, BOARD B, APPLICANT A WHERE M.MNUM = B.MNUM and A.MNUM = B.MNUM and B.BNUM=? ORDER BY M.MNUM asc";

}
